from sqlalchemy.orm import Mapped, mapped_column
from sqlalchemy import String, Text, Integer, Float, DateTime, JSON, ForeignKey
from datetime import datetime, timezone
from db import Base

class CompanyReport(Base):
    \"\"\"Stores the weekly analytics reports generated by the CEO Agent.\"\"\"
    __tablename__ = \"company_reports\"
    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    client_id: Mapped[int] = mapped_column(ForeignKey(\"clients.id\"), index=True)
    report_date: Mapped[datetime] = mapped_column(DateTime, default=lambda: datetime.now(timezone.utc))
    metrics: Mapped[dict] = mapped_column(JSON) # {total_leads, conv_rate, avg_response_time, etc}
    summary: Mapped[str] = mapped_column(Text)
    hot_leads: Mapped[List[str]] = mapped_column(JSON) # List of phone numbers
    drop_off_point: Mapped[str] = mapped_column(String(255))

class QALog(Base):
    \"\"\"Stores the quality assurance grades for sampled conversations.\"\"\"
    __tablename__ = \"qa_logs\"
    id: Mapped[int] = mapped_column(primary_key=True, autoincrement=True)
    conversation_id: Mapped[int] = mapped_column(ForeignKey(\"conversations.id\"), index=True)
    client_id: Mapped[int] = mapped_column(ForeignKey(\"clients.id\"), index=True)
    grade: Mapped[float] = mapped_column(Float) # 0.0 to 1.0
    feedback: Mapped[str] = mapped_column(Text)
    rag_used_correctly: Mapped[bool] = mapped_column(Boolean, default=True)
    escalation_missed: Mapped[bool] = mapped_column(Boolean, default=False)
    reviewed_at: Mapped[datetime] = mapped_column(DateTime, default=lambda: datetime.now(timezone.utc))
